### ISSUE TITLE
Error immediately after installing via Docker

### ISSUE THREAD

**Issue by loosus** [MysticRyuujin/guac-install#183]
Here are the steps I followed to the best of my knowledge:

1. Created a new virtual machine in ESXi 7.0.
2. Downloaded the following ISO for Debian: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.9.0-amd64-xfce-CD-1.iso
3. Installed Debian into the virtual machine using that ISO.  During the installation, I chose not to install any of the desktop GUIs but _did_ opt to install the "standard system utilities" and the "SSH server."
4. Logged into Debian as root.
5. At the Debian command prompt, I issued these commands

> wget https://raw.githubusercontent.com/MysticRyuujin/guac-install/0816002f0c4a99557fe513029c75d0ca115ea10f/docker-install.sh
> chmod +x docker-install.sh
> ./docker-install.sh

6. During the installation, I answered the questions that were prompted, such as MySQL passwords.
7. During the installation, the only message that looked suspicious to me was this one:
```
Waiting for MySQL to be healthy
ERROR 2013 (HY000): Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11
```

After installation, I visited http://[IPAddress]:8080/guacamole/ and get the following message:

> An error has occurred and this action cannot be completed. If the problem persists, please notify your system administrator or check your system logs.

Things I tried:

1. Rebooting the VM.
2. Disabling the firewall.
3. Restarting the containers manually.

The command "docker ps" shows the following:

```
CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS                    PORTS                                                  NAMES
4eabaa5fb97a   guacamole/guacamole   "/opt/guacamole/bin/…"   21 minutes ago   Up 19 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp              guacamole
41b9f6878c13   guacamole/guacd       "/bin/sh -c '/usr/lo…"   22 minutes ago   Up 19 minutes (healthy)   4822/tcp                                               guacd
650f68975e6f   healthcheck/mysql     "docker-entrypoint.s…"   22 minutes ago   Up 19 minutes (healthy)   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   mysql
```

Just for kicks, I recreated the VM with another Debian ISO and followed the above steps but got exactly the same result.

**Comment by MysticRyuujin** [comment]
Can you give me the logs of the mysql container?

`docker logs mysql`

**Comment by loosus** [comment]
```
2021-06-06 06:53:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-06-06 06:53:08+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-06-06 06:53:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-06-06 06:53:08+00:00 [Note] [Entrypoint]: Initializing database files
2021-06-06T06:53:08.535719Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.25) initializing of server in progress as process 42
2021-06-06T06:53:08.545680Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-06T06:53:09.578161Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-06T06:53:12.121249Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2021-06-06 06:53:16+00:00 [Note] [Entrypoint]: Database files initialized
2021-06-06 06:53:16+00:00 [Note] [Entrypoint]: Starting temporary server
2021-06-06T06:53:16.755702Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 87
2021-06-06T06:53:16.773504Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-06T06:53:17.371154Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-06T06:53:17.712977Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
2021-06-06T06:53:17.925583Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-06-06T06:53:17.925862Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-06-06T06:53:17.932980Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-06-06T06:53:17.971338Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
2021-06-06 06:53:17+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

2021-06-06 06:53:23+00:00 [Note] [Entrypoint]: Stopping temporary server
2021-06-06T06:53:23.797958Z 10 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.25).
2021-06-06T06:53:27.295902Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
2021-06-06 06:53:27+00:00 [Note] [Entrypoint]: Temporary server stopped

2021-06-06 06:53:27+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2021-06-06T06:53:28.107707Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
2021-06-06T06:53:28.119461Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-06T06:53:28.546950Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-06T06:53:28.762901Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2021-06-06T06:53:28.895085Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-06-06T06:53:28.895317Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-06-06T06:53:28.898361Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-06-06T06:53:28.928632Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2021-06-06T06:55:46.066756Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.25).
2021-06-06T06:55:47.327349Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
2021-06-06 06:56:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-06-06 06:56:15+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-06-06 06:56:15+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-06-06T06:56:15.678890Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
2021-06-06T06:56:15.728779Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-06T06:56:16.307288Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-06T06:56:16.605946Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2021-06-06T06:56:16.808456Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-06-06T06:56:16.808883Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-06-06T06:56:16.821781Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-06-06T06:56:16.884240Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2021-06-06T06:57:33.722386Z 10 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
2021-06-06T06:57:33.780804Z 11 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
2021-06-06T07:16:46.212238Z 50 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
2021-06-06T07:16:46.273394Z 51 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
```

**Comment by MysticRyuujin** [comment]
Ok I think I know what the problem is, the script wasn't properly waiting for mysql to be ready...I think...

If your VM is still up can you try running this:

```bash
# REPLACE THESE:
guacdbuserpassword="YOUR_guacdbuserpassword_PASSWORD"
mysqlrootpassword="YOUR_mysqlrootpassword_PASSWORD"
```
```bash
GUACVERSION="1.3.0"
SERVER="http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/${GUACVERSION}"
wget -O guacamole-auth-jdbc-${GUACVERSION}.tar.gz ${SERVER}/binary/guacamole-auth-jdbc-${GUACVERSION}.tar.gz
tar -xzf guacamole-auth-jdbc-${GUACVERSION}.tar.gz

SQLCODE="
create database guacamole_db;
create user 'guacamole_user'@'%' identified by '$guacdbuserpassword';
GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole_db.* TO 'guacamole_user'@'%';
flush privileges;"

echo $SQLCODE | mysql -h 127.0.0.1 -P 3306 -u root -p$mysqlrootpassword
cat guacamole-auth-jdbc-${GUACVERSION}/mysql/schema/*.sql | mysql -u root -p$mysqlrootpassword -h 127.0.0.1 -P 3306 guacamole_db

docker container restart guacamole
```

Alternatively, you can just re-install from the newest version, I pushed a possible fix...

**Comment by goekem** [comment]
I just tried to use the updated script (it had failed on me the same way the other day and I just ended up hand-jamming the SQL code in). It seems to get hung up on "Waiting for MySQL to be healthy".

output from `docker logs mysql`

`2021-06-08 01:39:25+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-06-08 01:39:25+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-06-08 01:39:25+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
2021-06-08 01:39:26+00:00 [Note] [Entrypoint]: Initializing database files
2021-06-08T01:39:26.060785Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.25) initializing of server in progress as process 41
2021-06-08T01:39:26.066038Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-08T01:39:41.093904Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-08T01:40:14.263416Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2021-06-08 01:41:25+00:00 [Note] [Entrypoint]: Database files initialized
2021-06-08 01:41:25+00:00 [Note] [Entrypoint]: Starting temporary server
2021-06-08T01:41:25.683149Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 113
2021-06-08T01:41:25.763435Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-08T01:41:26.942735Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-08T01:41:27.360903Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
2021-06-08T01:41:28.994613Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-06-08T01:41:28.994971Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-06-08T01:41:29.181759Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-06-08T01:41:29.381112Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
2021-06-08 01:41:29+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

2021-06-08 01:41:39+00:00 [Note] [Entrypoint]: Stopping temporary server
2021-06-08T01:41:39.085603Z 10 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.25).
2021-06-08T01:42:08.076766Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.25)  MySQL Community Server - GPL.
2021-06-08 01:42:08+00:00 [Note] [Entrypoint]: Temporary server stopped

2021-06-08 01:42:08+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2021-06-08T01:42:08.395320Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
2021-06-08T01:42:08.428118Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-06-08T01:42:09.909249Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2021-06-08T01:42:10.253633Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2021-06-08T01:42:11.202990Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-06-08T01:42:11.203151Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-06-08T01:42:11.356215Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2021-06-08T01:42:11.374995Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.`

**Comment by goekem** [comment]
Deleted my last comment due to a layer 8 issue...
Patch is confirmed working on Ubuntu Server 20.04

Been using your scripts for years. Thanks for all the work you put into them!

**Comment by loosus** [comment]
Still failed form me.  However, the installation messages are different this time.  I've highlighted the part I thought was interesting.  It stayed on "Waiting for MySQL to be healthy" for about 45 seconds before proceeding.

```
Unable to find image 'healthcheck/mysql:latest' locally
latest: Pulling from healthcheck/mysql
69692152171a: Pull complete
1651b0be3df3: Pull complete
951da7386bc8: Pull complete
0f86c95aa242: Pull complete
37ba2d8bd4fe: Pull complete
6d278bb05e94: Pull complete
497efbd93a3e: Pull complete
f7fddf10c2c2: Pull complete
16415d159dfb: Pull complete
0e530ffc6b73: Pull complete
b0a4a1a77178: Pull complete
cd90f92aa9ef: Pull complete
333b33290c54: Pull complete
Digest: sha256:b7a7b38485b0d93bfc12a42f870dcf8b27c9ba854c9a28d4d26ed941a113ee20
Status: Downloaded newer image for healthcheck/mysql:latest
3e5399d175aa4b2905b086c0e99745d01a65a7d4c3f5041accba7bf6010e67ae
**Waiting for MySQL to be healthy
ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory**
Unable to find image 'guacamole/guacd:latest' locally
latest: Pulling from guacamole/guacd
6ec7b7d162b2: Pull complete
c06d995d9f97: Pull complete
c71cb12da6c3: Pull complete
1d43fcdb5a3d: Pull complete
cd4d32047a00: Pull complete
2bb2b6f4ac15: Pull complete
b61892b7fbd5: Pull complete
Digest: sha256:49d43948140f03956124abce4fd8d7e002d61fb19d4c7ca79fcc1638900b0fd1
Status: Downloaded newer image for guacamole/guacd:latest
680d1dca2b53810065ce425158788a0af511f48af3f73f39caa4c14cf6bf38b8
Unable to find image 'guacamole/guacamole:latest' locally
latest: Pulling from guacamole/guacamole
6c33745f49b4: Pull complete
ef072fc32a84: Pull complete
c0afb8e68e0b: Pull complete
d599c07d28e6: Pull complete
e8a829023b97: Pull complete
2709df21cc5c: Pull complete
3bfb431a8cf5: Pull complete
bb9822eef866: Pull complete
38bfa20994f8: Pull complete
ab674e75b020: Pull complete
415b4c690028: Pull complete
18f7d9b5b979: Pull complete
Digest: sha256:739cb6820ae884827ceaaa87b45b8802769649c848d737584aea79d999177dc3
Status: Downloaded newer image for guacamole/guacamole:latest
3398c25713a514d1b727d9dbe07c4e6c6ae1cda6b0d7d254bce3f861825811d6
Cleanup install files...

Installation Complete
```

**Comment by MysticRyuujin** [comment]
Ok, soooo this seems to be some kind of authentication plugin issue related to updates...

Can you modify line 94?

From:
```bash
docker run --restart=always --detach --name=mysql --env="MYSQL_ROOT_PASSWORD=$mysqlrootpassword" --publish 3306:3306 healthcheck/mysql
```
To:
```bash
docker run --restart=always --detach --name=mysql --env="MYSQL_ROOT_PASSWORD=$mysqlrootpassword" --publish 3306:3306 healthcheck/mysql --default-authentication-plugin=mysql_native_password
```

The re-run it, and see if that does anything different?

**Comment by MysticRyuujin** [comment]
From what I can tell, the issue seems to be a difference in version between the `default-mysql-client` that debian installs, and the version of mysql that gets pulled via docker. Docker has a new version, debian has an older version, and there's support miss-match.

The workaround above is adding `--default-authentication-plugin=mysql_native_password` to mysql when it stats, which should solve the problem until more clients get updates to support it...

What a shit show lol

**Comment by loosus** [comment]
I haven't done extensive testing to make sure everything works, but I am definitely able to login now.  Thanks so much.

Is it possible for you to check the version of MySQL installed and script around that?

**Comment by MysticRyuujin** [comment]
It's certainly possible but I'm lazy lol
